---
title: "Week 8 Notes - Predictive Policying, Dirty Data, and Count Regression"
date: "2025-11-3"
---

## Key Concepts Learned
- Broken Window's Theory: Signs of disorder (abandoned cars) predict property crime (burglaries)
- Global v. Local Spatial Autocorrelation: Moran's I (diff formulas for each)
  - Use Moran's I scatterplot to visualize hotspots/coldspots and outliers
- Statistical Significance Testing:
  - Calculate observed I_i for location 𝑖
  - Randomly shuffle values across locations (999 times)
  - Recalculate I_i for each permutation
  - Compare observed vs. distribution of permuted values
  - If observed is extreme → statistically significant (p < 0.05)
- Why linear regression does not work for "count" target data:
  - Can predict negative values (impossible for counts)
  - Assumes constant variance (counts often have variance ≠ mean)
  - Assumes continuous outcome (counts are discrete)
  - Assumes normal errors (count data is skewed)
- Model 1: Poisson
  - Raise e to the power of sum of regressors
  - Log-scaled
- Over-Dispersion Problem: Variance >>> Mean
  - Unobserved heterogeneity: Some areas have unmeasured crime attractors
  - Contagion effects: One crime leads to others (not independent)
  - Measurement error: Counting issues, data quality
  - Model misspecification: Missing important variables
  - Dispersion = Residual Deviance / Degrees of Freedom
- Model 2: Negative Bibomial (for over-dispersion)
  - Relaxes variance = mean assumption
- Fishnet Grid: 
  - Standard approach in predictive policing
  - Easier spatial operations
  - Consistent unit of analysis
- LOGO-CV: Leave-one-out CV for spatial data
- Kernel Density Estimation (KDE): Simpleset spatial prediction method
  - Place smooth “bump” over each crime location
  - Sum all bumps to create risk surface
  - No predictors, no model, just past locations


## Coding Techniques

## Questions & Challenges
- Nothing!

## Connections to Policy
- Understanding dirty data is very important for preventing algorithmic biases in our modeling process.

## Reflection
- Re-learning the Poisson and Negative Binomial regression methods is important especially for cases like Crime count data.

