project:
  type: website
  output-dir: docs

website:
  title: "Henry (Jack) Bader - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: weekly-notes/
        text: "Weekly Notes"
        menu:
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"
          - href: weekly-notes/week-03-notes.qmd
            text: "Week 3"
          - href: weekly-notes/week-04-notes.qmd
            text: "Week 4"
      - href: labs/
        text: "Labs"
      - href: assignments/ 
        text: "Assignments"
        menu:
          - href: assignments/
            text: "All Assignments"
          - href: assignments/assignment1/assignment1.qmd
            text: "Assignment 1"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
