{
  "hash": "20568e95b88f88598002a18ff5ebcb37",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Assignment 4: Spatial Predictive Analysis\"\nformat: html\n---\n\n# Setup\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(readr)\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\nlibrary(here)\n\n# Spatstat split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create consistent theme for visualizations\ntheme_plotting <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n```\n:::\n\n\n# Part 1: Data Loading & Exploration\n\n## 1.1 Data Loading\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\", quiet = TRUE) |>\n  st_transform('ESRI:102271') |>\n  dplyr::select(District = dist_num)\n\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\", quiet = TRUE) |>\n  st_transform('ESRI:102271') |>\n  dplyr::select(Beat = beat_num)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\", quiet = TRUE) |>\n  st_transform('ESRI:102271')\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load burglaries data\nburglaries <- st_read(\"/Users/jack/Documents/GitHub/portfolio-setup-jbader14/assignments/assignment4/data/burglaries.shp\", quiet = TRUE) |>\n  st_transform('ESRI:102271')\n```\n:::\n\n\n::: callout-note\n## Burglary Data\n\n**Data Source:** \n\nThe Chicago Police Department (CPD) provides the data on reported burglaries, where each row represents a distinct burglary incident in the city of Chicago from 2017.\n\n**Data Quality Concerns:**\n\n- **Patrol Biases:** Neighborhoods in Chicago that experience a higher volume of police patrolling may experience more reported burglaries as a result.\n\n- **Under-reported / Missing Data:** Some burglaries may not have been reported due to external circumstances, such as in neighborhoods with a higher distrust of law enforcement or ignored complaints.\n\n- **Consistent Reporting:** The CPD may not report all burglary incidents into their database or possibly code them as different crimes either by error or intentionally.\n\n**Considerations:**\n\nIt is important to consider the potential biases that arise in police reported data. These are crucial examples of potential \"dirty data\" instances that must be recognized before continuing with our model building workflow. Crime data that is biased and non-neutral cannot be remedied by traditional technical data cleaning to seperate true crime from policing patterns, so we must proceed with caution.\n\nOur largest concern is the data may adversely affect over-policed communities in Chicago, potentially skewing our data to show these neighborhoods as more prominent \"burglary hotspots\". It may not be that these neighborhoods are truly more susceptible to burglaries but that they are more policed and reported. This is a classic case of a feedback loop where over-policed neighborhoods are identified as high-risk for burglaries by our algorithm. As a result, more police units are sent there leading to even more burglary reports, repeating the cycle.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Selected 311 data: All Streetlights Out\nstreetlights <- read_csv(\"/Users/jack/Documents/GitHub/portfolio-setup-jbader14/assignments/assignment4/data/streetlights.csv\")\n```\n:::\n\n\n## 1.2 Data Cleaning\n\n::: {.cell}\n\n```{.r .cell-code}\nstreetlights <- streetlights |>\n  # Filter out streetlights with no location data\n  filter(!is.na(Location)) |>\n  # Create new variable creation_date in datetime type\n  mutate(\n    creation_date = mdy(`Creation Date`)\n  ) |>\n  # Filter for only 2017 complaints\n  filter(\n    creation_date >= as.Date(\"2017-01-01\"),\n    creation_date <  as.Date(\"2018-01-01\")\n  )\n\n# Convert to sf\nstreetlights <- st_as_sf(streetlights, coords = c(\"Longitude\", \"Latitude\"), crs = 4326) |>\n  st_transform('ESRI:102271')\n```\n:::\n\n\n::: callout-note\n## 311 Street Lights (All Out) Data\n\n**Data Source:** \n\nThe city of Chicago provides data on their 311 service request line for various offenses. The street lights (all out) dataset represents incidents where there is an outage of 3 or more lights in a city circuit, where each circuit typically has 8-16 streetlights. \n\n**Modeling Choice of Street Lights (All Out):** \n\nWe decided to use street lights (all out) as our 311 offense variable over other types such as graffiti or pothole incidents because we believe it is a better choice of a predictor for modeling burglary risk in Chicago. Assuming that most burglaries tend to occur at night, city blocks without working streetlights are seen as much more at risk for burglaries since it is harder to surveil the surrounding environment due to the lack of visibility. Also, streetlight outages can occur in distinct clustering patterns based on the dataset description that make it a suitable choice for modeling burglary hotspots.\n\n**Data Cleaning:**\n\n1. For spatial analysis, we filtered out any incidents that failed to report a location.\n\n2. To remain consistent with the burglaries dataset, we filtered the street lights (all out) dataset to only include reports in the same year (2017).\n\n**Data Quality Concerns:** \n\nOne potential concern is the presence of duplicate service requests. The general procedure is for the city to send an electrician to repair the broken lights in a circuit after a request is made. However, the city emphasizes that sometimes a second request is put out for the same outage if it was not repaired properly, leading to duplicate requests in our dataset. This issue can be tied to poor city infrastructure that can impact the data quality we are using in our analysis. We will make note of it as this could overestimate pockets with high frequencies of broken streetlights due to poor data reporting and repair management. Additionally as before, reporting of 311 incidents may not be consistent across neighborhoods in Chicago for external reasons such as a lack of time to report, lack of care, etc.\n\n**Considerations:** \n\nIt is important to recognize these data quality concerns as we can use this variable as a proxy for **dark city blocks with poor visibility** but also recognizing that other variables such as duplicates and reporting inconsistencies may skew the accuracy of our analysis and models.\n:::\n\n## 1.3 Spatial Visualizations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = burglaries, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Burglary Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(burglaries))\n  ) +\n  theme_plotting()\n\n# Density surface using modern syntax\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(burglaries)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  ) +\n  theme_plotting()\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Burglaries in Chicago\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/burglaries-spatial-visualizations-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = streetlights, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Streetlight Outages Locations\",\n    subtitle = paste0(\"Chicago 2019, n = \", nrow(streetlights))\n  ) +\n  theme_plotting()\n\n# Density surface using modern syntax\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(streetlights)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel Density Estimation (KDE)\"\n  ) +\n  theme_plotting()\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Street Lights (All Out) in Chicago\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/streetlights-spatial-visualizations-1.png){width=672}\n:::\n:::\n\n\n::: callout-note\n## Spatial Visualizations Interpretation\n\n**What we did:**  \n\nWe created side by side point-geometry and KDE density maps for Chicago burglaries and street lights (all out):\n\n1. The point estimates show the exact locations to demonstrate the distribution of burglaries and broken street lights throughout Chicago.\n\n2. The **Kernel Density Estimation (KDE)** maps show a better high-level understanding of spatial patterns from a smoothed heatmap of burglaries and broken street lights.\n\n**Why this step matters:**\n\nIt is important to visualize how our target and predictor variables are spatially distributed across Chicago before we move onto further analysis and eventual modeling phases. This step helped support our decision to use street lights (all out) to better understand burglaries since their heatmaps show similar hotspot regions.\n\n**Why this step is important:**\n\nFor both variables, we see similar clusters of hotspots across the city of Chicago from the KDE plots. They both exhibit a large Northern hotspot and two Southern hotspots across the city that align close to one another. This evidence suggests that there could be a presence of positive correlation between neighborhoods that experience lots of streetlight blackouts and higher burglary incidents. We want correlation between our target and regressor variable when building a model to accurately predict burglary counts in Chicago.\n:::\n\n\n# Part 2: Fishnet Grid Creation\n\n## 2.1 Create a 500m vs. 500m Fishnet Grid\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 m\n  square = TRUE\n) |>\n  st_sf() |>\n  mutate(uniqueID = row_number())\n\n# Keep only cells that intersect Chicago\nfishnet <- fishnet[chicagoBoundary, ]\n```\n:::\n\n\n## 2.2 Aggregate Your Violations to Grid Cells\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join: which cell contains each burglary?\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) |>\n  st_drop_geometry() |>\n  group_by(uniqueID) |>\n  summarize(countBurglaries = n())\n\n# Join back to fishnet (cells with 0 burglaries will be NA)\nfishnet <- fishnet |>\n  left_join(burglaries_fishnet, by = \"uniqueID\") |>\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n# Summary statistics\ncat(\"\\nBurglary count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBurglary count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countBurglaries)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   0.000   2.000   3.042   5.000  40.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero burglaries:\", \n    sum(fishnet$countBurglaries == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countBurglaries == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero burglaries: 781 / 2458 ( 31.8 %)\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join to determine how many streetlights complaints in each cell\nstreetlights_fishnet <- st_join(streetlights, fishnet, join = st_within) |>\n  st_drop_geometry() |>\n  group_by(uniqueID) |>\n  summarize(countStreetlights = n())\n\n# Join back to fishnet\nfishnet <- fishnet |>\n  left_join(streetlights_fishnet, by = \"uniqueID\") |>\n  mutate(countStreetlights = replace_na(countStreetlights, 0))\n\n# Print Summary Stats\ncat(\"\\nStreetlight count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nStreetlight count distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$countStreetlights)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  0.000   1.000   5.000   5.931   9.000  42.000 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"\\nCells with zero streetlight incidents:\", \n    sum(fishnet$countStreetlights == 0), \n    \"/\", nrow(fishnet),\n    \"(\", round(100 * sum(fishnet$countStreetlights == 0) / nrow(fishnet), 1), \"%)\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCells with zero streetlight incidents: 437 / 2458 ( 17.8 %)\n```\n\n\n:::\n:::\n\n\n## 2.3 Visualize the Count Distribution\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get medians\nburg_med  <- median(fishnet$countBurglaries, na.rm = TRUE)\nstreet_med <- median(fishnet$countStreetlights, na.rm = TRUE)\n\n# burglary histogram\np_burg_hist <- ggplot(fishnet, aes(x = countBurglaries)) +\n  geom_histogram(bins = 40, fill = \"maroon\", color = \"black\") +\n  geom_vline(xintercept = burg_med, linetype = 5) +\n  annotate(\n    \"text\",\n    x = burg_med,\n    y = Inf,\n    label = \"Median\",\n    vjust = 1.5,\n    hjust = -0.1,\n    size = 3\n  ) +\n  labs(\n    title = \"Burglaries\",\n    subtitle = \"For 500m fishnet cells\"\n  ) +\n  theme_plotting()\n\n# streetlight histogram \np_street_hist <- ggplot(fishnet, aes(x = countStreetlights)) +\n  geom_histogram(bins = 40, fill = \"skyblue\", color = \"black\") +\n  geom_vline(xintercept = street_med, linetype = 5) +\n  annotate(\n    \"text\",\n    x = street_med,\n    y = Inf,\n    label = \"Median\",\n    vjust = 1.5,\n    hjust = -0.1,\n    size = 3\n  ) +\n  labs(\n    title = \"Streetlights\",\n    subtitle = \"For 500m fishnet cells\"\n  ) +\n  theme_plotting()\n\np_burg_hist + p_street_hist + \n    plot_annotation(\n    title = \"Aggregated Count Distributions in Chicago (2017)\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/count-distribution-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np_burg <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Burglaries\",\n    option = \"plasma\",\n    trans = \"sqrt\",\n    breaks = c(0, 1, 5, 10, 20, 40)\n  ) +\n  labs(\n    title = \"Burglary Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_plotting()\n\np_street <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countStreetlights), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Streetlights\",\n    option = \"plasma\",\n    trans = \"sqrt\",\n    breaks = c(0, 1, 5, 10, 20, 40)\n  ) +\n  labs(\n    title = \"Streetlight Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_plotting()\n\np_burg + p_street +\n  plot_annotation(\n    title = \"Counts Aggregated to 500m Fishnet Cells\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/spatial-count-distribution-1.png){width=960}\n:::\n:::\n\n\n::: callout-note\n## Fishnet Grid Creation (500m Aggregation)\n\n**What we did:**  \n\n1. First, we created a fishnet grid of 500m by 500m to overlay over Chicago. Each cell in the grid is of equal size in the fishnet rather than if we overlayed by zip code or district.\n\n2. Secondly, we conducted a spatial join with burglaries and streetlight requests and computed the total count of each variable within each cell in the fishnet grid.\n\n3. Lastly, we plotted spatial maps showing the aggregate counts of burglaries and broken streetlights side by side for comparison. We also included histogram plots to visualize the count distributions for each variable for grid cells as well.\n\n**What we found:**  \n\nBoth counts of burglaries and broken streetlights are sparse. The cause of this is due to our cell size only being 500m by 500m. Some cells may cover non-residential areas where burglaries don't occur or areas that do not contain any streetlights such as parks: \n\n- 781 of 2,458 cells (32%) had **zero** burglaries.  \n    \n- 437 of 2,458 cells (18%) had **zero** streetlight requests.\n    \nWe also found that the aggregated counts for both burglaries and streetlight requests were right-skewed. This indicates that there are cells that experience abnormally high numbers of burglaries or streetlight outages, compared to the rest of the grid. This right-skew pattern is typical in count data as smaller counts are observed most frequently. The variance seems quite large for both metrics, which is an early indication that a negative binomial model may be preferred over a poisson regression.\n\nThere seems to be a wider spread of grid cells experiencing high streetlight outages than burglaries. This makes sense since there are more reports of broken streetlights than burglaries from the data we are using. Generally, there still seems to be some pattern between the two that we look to further explore.\n\n**Why this step is important:**\n\nThe modeling decision to use a fishnet grid is necessary for modeling burglaries and streetlights as areas rather than points for a spatial regression. The histogram plots confirmed that both burglaries and broken streetlights fall under count data; in other words, there are no negative or non-integer values for these two variables.\n\nFor the fishnet grid, having cells of equal area and identical shape makes our aggregated counts of burglaries and streetlights across cells more directly comparable. If we had used zip codes or districts, there would be an inherent size bias where larger areas experience more burglaries and streetlights. A disadvantage of this approach is that these grids are not representative of real-world social or policy boundaries. We lose out on neighborhood specific qualities that may be beneficial in modeling burglary activity. Also, it may be harder to identify specific districts of need that require target policies to address burglary concerns.\n:::\n\n# Aside: Create a Kernel Density Baseline\n\n::: {.cell}\n\n```{.r .cell-code}\n# Convert burglaries to ppp (point pattern) format for spatstat\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_burglaries)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot() +\n  geom_sf(data = fishnet, aes(fill = kde_value), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"KDE Value\",\n    option = \"plasma\"\n  ) +\n  labs(\n    title = \"Kernel Density Estimation Baseline\",\n    subtitle = \"Simple spatial smoothing of burglary locations\"\n  ) +\n  theme_plotting()\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/kde-visualization-1.png){width=768}\n:::\n:::\n\n::: callout-note\n## KDE Baseline\n\n**What we did:**  \n\nWe built a **Kernel Density Estimation (KDE)** with a 1 km kernel bandwidth to serve as our baseline model to reference throughout our analysis. This baseline is simple by taking historical reported burglary data without any other predictor variables. We visualized our baseline model in our plot by smoothing the KDE spatial results over our fishnet grid. The 1 km bandwidth is an optimal choice for balancing capturing noisier, local patterns while providing smooth stablility and generalization.\n\n**What we found:** \n\n- The KDE baseline smooths out variation between cells, creating more discernable local burglary hotspots in Chicago. As before, we see a large Northern hotspot and two Southern ones.\n\n- Since this model does not take into account any external variables, we don't actually know why these hotspots appear in the data or what caused them. We only know that in Chicago in 2017, these regions had the most reported burglaries.\n\n**Why this step is important:**  \n\nEstablishing a simple baseline prior to constructing any sort of a predictive model serves as a crucial check for later evaluating model performance. In our case, a KDE model states that future burglaries are most likely to occur where there have been many past burglaries. Any more complex model should offer more predictive power to outperform our baseline such as factoring in our broken streetlights feature. Our goal is to use our 311 broken streetlights data to better predict future burglaries. Our hope is to use our findings to advocate for targeted policy measures more streetlights, better repair services etc.\n:::\n\n\n# Part 3: Spatial Features\n\n## 3.1 Calculate k-nearest neighbor features\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate mean distance to 3 nearest reports of broken streetlights\n\n# Get coordinates\nstreetlights_coords <- st_coordinates(streetlights)\nfishnet_coords <- st_coordinates(st_centroid(fishnet))\n\n# Calculate k nearest neighbors and distances\nknn_results <- get.knnx(streetlights_coords, fishnet_coords, k = 3)\n\n# Add to fishnet\nfishnet <- fishnet |>\n  mutate(\n    streetlights_knn = rowMeans(knn_results$nn.dist)\n  )\n\ncat(\"\\nK-NN (K = 3) for closest broken streetlights distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nK-NN (K = 3) for closest broken streetlights distribution:\n```\n\n\n:::\n\n```{.r .cell-code}\nsummary(fishnet$streetlights_knn)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  11.12  116.95  173.40  244.12  274.62 1651.04 \n```\n\n\n:::\n:::\n\n\n## 3.2 Perform Local Moran's I Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  # Calculate Local Moran's I\n  local_moran <- localmoran(data[[variable]], weights)\n  \n  # Classify clusters\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data |>\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Apply to graffiti\nfishnet <- calculate_local_morans(fishnet, \"countStreetlights\", k = 5)\n```\n:::\n\n\n## 3.3 Identify Hot Spots & Cold Spots\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Streetlight Outage Clusters\",\n    subtitle = \"High-High = Hot spots of disorder\"\n  ) +\n  theme_plotting()\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/unnamed-chunk-1-1.png){width=768}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  - Number of hot spot cells: 186 \n```\n\n\n:::\n:::\n\n\n\n::: callout-note\n## Spatial Features\n\n**What we did:**  \n\nIn this section, we engineered spatial features that help us get a better understanding of the distribution of burglary clusters and its relationship to streetlight outages in Chicago.\n\n1. First, we created the variable streetlights_knn, which is the average distance to the nearest three streetlight outage reports for each cell centroid in our fishnet grid.\n\n2. Secondly, we used Local Moran's I to gain a better understanding of the distribution of streetlight outage clusters throughout Chicago, identifying potential hotspots, coldspots, and outliers.\n\n3. Lastly, we constructed a variable dist_to_hotspot as the distance from a cell to the nearest streetlight outage hotspot.\n\n\n**What we found:**  \n\n- The **Local Moran’s I map** shows streetlight outage hotspots (high-high, red), coldspots (low-low, blue), and outliers (low-high, light blue and high-low, orange). The colored sections are statistically significant whereas non-colored sections are due to random chance as they did not pass the permutation test for significance.\n\n  - We see a large cluster of low-low coldspots (blue) in south Chicago where these cells do not experience many streetlight outages, and their surrounding cells also do not observe many outages. In other words, the blue cells and their neighbor cells experience below-average outages compared to all cells in the grid.\n  \n  - There are a considerable amount of smaller high-high hotspots (red) scattered throughout the Central Chicago area. As the name suggests, the red cells experience above average streetlight outages and their neighbors do as well.\n  \n  - There are few low-high or high-low outliers throughout Chicago. Intuitively, this makes sense due to spatial dependence of outages. Streetlight outages are either likely to cluster in the same areas or not occur much at all in the same areas.\n\n- Our engineered spatial features of **streetlights_knn** and **dist_to_hotspot** will provide our model with more detail than just using the aggregate number of streetlight outages in each cell. Exploring the spatial relationships and dependencies between burglaries and streetlight outages can provide our model with a better understanding in making accurate predictions.\n\n**Why this step is important:**  \n\nFor our modeling workflow, we need to take into account spatial features as indicators of disorder that can help us in predicting burglaries in Chicago. The fundamental idea is that neighborhoods share similar crime levels in historical data. Creating spatial features can help us model patterns in burglary activity. Incorporating spatial features can better account for spatial dependence, generate more accurate predictions, and capture local spillover effects:\n\n- **streetlights_knn:** This variable supports our intuition that more burglaries may occur in areas that are closer to reported multiple streetlight blackouts where visibility is dampened. Our goal is that this feature is a strong predictor of burglaries in our modeling phase.\n\n- **Local Moran's I:** This method allows us to visualize significant streetlight outage clusters across Chicago. These hotspots are used as a proxy for disorder that can drive up burglary risk in that area, reflective of the Broken Windows theory.\n\n- **dist_to_hotspot**: We take our findings from the Local Moran's I test to engineer this feature to the nearest streetlight outage hotspot. This is another metric to use in conjunction with our knn feature to bolster the spatial predictive power of streetlight outages in our model.\n\n:::\n\n# Part 4: Count Regression Models\n\n## 4.1 Fit Poisson Regression\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))  # Remove cells outside districts\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create clean modeling dataset\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    countStreetlights,\n    streetlights_knn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()  # Remove any remaining NAs\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Poisson regression\nmodel_poisson <- glm(\n  countBurglaries ~ countStreetlights + streetlights_knn + \n    dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\n# Summary\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ countStreetlights + streetlights_knn + \n    dist_to_hotspot, family = \"poisson\", data = fishnet_model)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-3.7277  -1.6005  -0.6064   0.7202  11.1338  \n\nCoefficients:\n                      Estimate   Std. Error z value             Pr(>|z|)    \n(Intercept)        1.907111377  0.048699661  39.161 < 0.0000000000000002 ***\ncountStreetlights  0.008627022  0.002779913   3.103              0.00191 ** \nstreetlights_knn  -0.002985175  0.000176953 -16.870 < 0.0000000000000002 ***\ndist_to_hotspot   -0.000111247  0.000009055 -12.285 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6710.3  on 1707  degrees of freedom\nResidual deviance: 5491.0  on 1704  degrees of freedom\nAIC: 9559.4\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n## 4.2 Fit Negative Binomial Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) / \n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 3.59 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n⚠ Overdispersion detected! Consider Negative Binomial model.\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Negative Binomial model\nmodel_nb <- glm.nb(\n  countBurglaries ~ countStreetlights + streetlights_knn + \n    dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Summary\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ countStreetlights + streetlights_knn + \n    dist_to_hotspot, data = fishnet_model, init.theta = 1.381058742, \n    link = log)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.2460  -1.0439  -0.3428   0.3643   4.4867  \n\nCoefficients:\n                     Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)        2.07602154  0.09440722  21.990 < 0.0000000000000002 ***\ncountStreetlights  0.00542866  0.00584517   0.929                0.353    \nstreetlights_knn  -0.00412560  0.00030961 -13.325 < 0.0000000000000002 ***\ndist_to_hotspot   -0.00008647  0.00001553  -5.569         0.0000000257 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.3811) family taken to be 1)\n\n    Null deviance: 2338.8  on 1707  degrees of freedom\nResidual deviance: 1876.4  on 1704  degrees of freedom\nAIC: 7750.8\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.3811 \n          Std. Err.:  0.0743 \n\n 2 x log-likelihood:  -7740.7580 \n```\n\n\n:::\n:::\n\n\n## 4.3 Model Comparison (AIC)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Compare AIC (lower is better)\ncat(\"\\nModel Comparison:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nModel Comparison:\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Poisson AIC:\", round(AIC(model_poisson), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPoisson AIC: 9559.4 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Negative Binomial AIC:\", round(AIC(model_nb), 1), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNegative Binomial AIC: 7750.8 \n```\n\n\n:::\n:::\n\n\n::: callout-note\n## Count Regression Models: Poisson vs. Negative Binomial\n\n**What we did:**  \n\n- First, we conducted a spatial join between our fishnet dataset with police boundaries to use in part 5 for spatial cross-validation. We also created a seperate dataset for modeling that selected relevant columns while dropping shape geometry and remaining nulls.\n\n- We chose two regression models for count data, Poisson and Negative Binomial, to model burglaries in our fishnet grid. We checked for overdispersion as a clear indicator that the Negative Binomial model is more suitable than the Poisson. \n\n- Our predictor variables for both regression models were:\n\n  - The number of reported streetlight outages (countStreetlights)\n  \n  - The average distance to the three nearest streetlight outages (streetlights_knn)\n  \n  - The distance to the nearest streetlight hotspot (dist_to_hotspot)\n  \n- Lastly, we used Akaike Information Criteria (AIC) as a final evaluation metric to compare our models.\n\n**What we found:**  \n\n- For both models, we found that the spatial regressors streetlight_knn and dist_to_hotspot were statistically significant at any reasonable confidence level with a negative effect on burglary counts. In other words, burglaries tended to be lower in locations that were further away from nearby streetlight outages or outage hotspots.\n\n- Conversely, streetlight counts were not statistically significant for the Negative Binomial model with a positive effect on predicted burglary counts. This supports our intuition that proximity to streetlight outages (spatial features) are much better predictors to use in our models than simple counts. If this variable were significant, it would suggest that more streetlight outages in a cell leads to a higher predicted burglary count.\n\n- We computed the overdispersion parameter to be 3.59, greater than our 1.5 threshold, suggesting a presence of overdispersion in our model. This violates the key assumption that variance = mean in a Poisson model, suggesting that the Negative Binomial model is the better choice. This is expected with crime data, which tends to have high variation.\n\n- We compared AIC scores across both models and found that the Negative Binomial model produces a better fit with a lower score of 7750.8 (Poisson with 9559.4). This confirms our initial findings from the overdispersion check that the Negative Binomial is the preferred model. This makes sense since the Negative Binomial model incorporates a dispersion parameter to capture excess variance in the modeling.\n\n**Why this step is important:**  \n\nFrom our count modeling phase, we gain a better understanding of the importance of spatial features in building a predictive model. We are also able to test our hypothesis of overdispersion to build our intuition that Negative Binomial models are better suited in most cases for crime-based count data. It also builds good evaluation practice in our modeling workflow using metrics such as AIC to compare goodness of fit to confirm our findings from the overdispersion test.\n:::\n\n# Part 5: Spatial Cross-Validation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique districts\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model on training data\n  model_cv <- glm.nb(\n    countBurglaries ~ countStreetlights + streetlights_knn + \n      dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict on test data\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, test_data, type = \"response\")\n    )\n  \n  # Calculate metrics\n  mae <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  # Store results\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n}\n\n# Overall results\ncat(\"Spatial CV - Mean MAE:\", round(mean(cv_results$mae), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial CV - Mean MAE: 2.76 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Spatial CV - Mean RMSE:\", round(mean(cv_results$rmse), 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nSpatial CV - Mean RMSE: 3.61 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Show results\ncv_results %>%\n  arrange(desc(mae)) %>%\n  kable(\n    digits = 2,\n    caption = \"LOGO CV Results by District\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>LOGO CV Results by District</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> fold </th>\n   <th style=\"text-align:left;\"> test_district </th>\n   <th style=\"text-align:right;\"> n_test </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 7 </td>\n   <td style=\"text-align:left;\"> 3 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 6.16 </td>\n   <td style=\"text-align:right;\"> 8.20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 12 </td>\n   <td style=\"text-align:left;\"> 12 </td>\n   <td style=\"text-align:right;\"> 73 </td>\n   <td style=\"text-align:right;\"> 3.58 </td>\n   <td style=\"text-align:right;\"> 4.79 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 4 </td>\n   <td style=\"text-align:left;\"> 6 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 3.35 </td>\n   <td style=\"text-align:right;\"> 4.67 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 14 </td>\n   <td style=\"text-align:left;\"> 11 </td>\n   <td style=\"text-align:right;\"> 43 </td>\n   <td style=\"text-align:right;\"> 3.31 </td>\n   <td style=\"text-align:right;\"> 3.89 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 8 </td>\n   <td style=\"text-align:left;\"> 2 </td>\n   <td style=\"text-align:right;\"> 56 </td>\n   <td style=\"text-align:right;\"> 3.04 </td>\n   <td style=\"text-align:right;\"> 3.67 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 5 </td>\n   <td style=\"text-align:left;\"> 8 </td>\n   <td style=\"text-align:right;\"> 197 </td>\n   <td style=\"text-align:right;\"> 2.94 </td>\n   <td style=\"text-align:right;\"> 3.83 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 6 </td>\n   <td style=\"text-align:left;\"> 7 </td>\n   <td style=\"text-align:right;\"> 52 </td>\n   <td style=\"text-align:right;\"> 2.91 </td>\n   <td style=\"text-align:right;\"> 3.74 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 10 </td>\n   <td style=\"text-align:left;\"> 10 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 2.83 </td>\n   <td style=\"text-align:right;\"> 3.61 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 15 </td>\n   <td style=\"text-align:left;\"> 18 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 2.81 </td>\n   <td style=\"text-align:right;\"> 3.91 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 17 </td>\n   <td style=\"text-align:left;\"> 14 </td>\n   <td style=\"text-align:right;\"> 46 </td>\n   <td style=\"text-align:right;\"> 2.73 </td>\n   <td style=\"text-align:right;\"> 3.93 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 16 </td>\n   <td style=\"text-align:left;\"> 25 </td>\n   <td style=\"text-align:right;\"> 85 </td>\n   <td style=\"text-align:right;\"> 2.71 </td>\n   <td style=\"text-align:right;\"> 3.86 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3 </td>\n   <td style=\"text-align:left;\"> 22 </td>\n   <td style=\"text-align:right;\"> 112 </td>\n   <td style=\"text-align:right;\"> 2.71 </td>\n   <td style=\"text-align:right;\"> 3.14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 22 </td>\n   <td style=\"text-align:left;\"> 24 </td>\n   <td style=\"text-align:right;\"> 41 </td>\n   <td style=\"text-align:right;\"> 2.64 </td>\n   <td style=\"text-align:right;\"> 3.64 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 11 </td>\n   <td style=\"text-align:left;\"> 1 </td>\n   <td style=\"text-align:right;\"> 28 </td>\n   <td style=\"text-align:right;\"> 2.42 </td>\n   <td style=\"text-align:right;\"> 2.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 2 </td>\n   <td style=\"text-align:left;\"> 4 </td>\n   <td style=\"text-align:right;\"> 235 </td>\n   <td style=\"text-align:right;\"> 2.27 </td>\n   <td style=\"text-align:right;\"> 3.90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 9 </td>\n   <td style=\"text-align:left;\"> 9 </td>\n   <td style=\"text-align:right;\"> 107 </td>\n   <td style=\"text-align:right;\"> 2.27 </td>\n   <td style=\"text-align:right;\"> 2.72 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 19 </td>\n   <td style=\"text-align:left;\"> 16 </td>\n   <td style=\"text-align:right;\"> 129 </td>\n   <td style=\"text-align:right;\"> 2.22 </td>\n   <td style=\"text-align:right;\"> 2.64 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 13 </td>\n   <td style=\"text-align:left;\"> 15 </td>\n   <td style=\"text-align:right;\"> 32 </td>\n   <td style=\"text-align:right;\"> 2.12 </td>\n   <td style=\"text-align:right;\"> 2.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 20 </td>\n   <td style=\"text-align:left;\"> 17 </td>\n   <td style=\"text-align:right;\"> 82 </td>\n   <td style=\"text-align:right;\"> 2.03 </td>\n   <td style=\"text-align:right;\"> 2.53 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 1 </td>\n   <td style=\"text-align:left;\"> 5 </td>\n   <td style=\"text-align:right;\"> 98 </td>\n   <td style=\"text-align:right;\"> 1.97 </td>\n   <td style=\"text-align:right;\"> 2.73 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 18 </td>\n   <td style=\"text-align:left;\"> 19 </td>\n   <td style=\"text-align:right;\"> 63 </td>\n   <td style=\"text-align:right;\"> 1.86 </td>\n   <td style=\"text-align:right;\"> 2.42 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 21 </td>\n   <td style=\"text-align:left;\"> 20 </td>\n   <td style=\"text-align:right;\"> 30 </td>\n   <td style=\"text-align:right;\"> 1.84 </td>\n   <td style=\"text-align:right;\"> 2.17 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n::: callout-note\n## Leave-One-Group-Out (LOGO) Spatial Cross-Validation (CV)\n\n**What we did:**  \n\nOur next step in our analysis is LOGO spatial cross-validation, looping over all police districts in Chicago. At each iteration (or fold), we train our Negative Binomial regression on all districts except one. We treat the heldout district as our test data to compute metrics of Mean Absolute Error (MAE) and Residual Mean Squared Error (RMSE) to evaluate how well our model did at predicting on the district that was not observed during training. We outputted our results from the spatial cross-validation above in order of decreasing MAE. \n\nA quick note, the choice for cross-validation on district rather than cell is an important decision made to prevent information leakage. If we were to use a regular Leave-One-Out (LOO) cross-validation for cells, then we would not truly be testing the model's ability to generalize to unseen data. There would likely not be enough cell-to-cell differentiation, leading to less meaningful results than if we had tied it back to real-world police districts.\n\n**What we found:**  \n\n- We found that MAE ranged from 1.84 to 6.16 and RMSE ranged from 2.17 to 8.20 respectively across all districts. We can interpret the mean MAE as we are off by 2.54 burglaries on average for each police district. Similarly, a mean RMSE of 3.33 places a higher penalty on larger errors. Since these metrics are relatively close in magnitude for most districts, we know that we did not have a lot of very bad predictions.\n\n- There does seem to be a clear pattern or trend in MAE/RMSE with respect to test district size.\n\n- The test districts with high MAE/RMSE is indicative that our Negative Binomial model performed worse at predicting burglaries here. There could be a few different explanations as to why this is the case. Likely, it is some combination of policing and reporting biases that occur in these districts that cannot be explained by our engineered spatial features of streetlights alone. \n\n- The model performed better on districts with low MAE/RMSE indicate that these districts correlate strongly with our streetlight spatial features. It also seems they are less affected by potential external biases left out of our modeling process.\n\n- It is worth noting that district 3 is a significant outlier where the model performed much worse on this district compared to the rest. After some brief research, this is a small district in Southeast Chicago where there seems to be the most missing data for burglary counts. Either this district is primarily non-residential buildings or reporting practices by the police are insufficient.\n\n**Why this step is important:**  \n\n- Spatial cross-validation is an essential step in building our predictive model to evaluate how well it generalizes to unseen districts. It gives us more valuable information on how the model performs on specific neighborhoods for more realistic policy interventions than non-spatial cross-validation. It also mitigates risk of adjacent/nearby correlated grid cells that cause spatial data leakage.\n\n- By clearly displaying the MAE/RMSE for each heldout district, we can see where our model fails and where it succeeds. This is a key building block for observing spatial dependence in our data as well as our model's limitations as we saw with the lack of data for District 3.\n:::\n\n# Part 6: Model Evaluation\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit final model on all data\nfinal_model <- glm.nb(\n  countBurglaries ~ countStreetlights + streetlights_knn + \n    dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Add predictions back to fishnet\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model, type = \"response\")[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\n# Also add KDE predictions (normalize to same scale as counts)\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create three maps\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_plotting()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (Neg. Binomial)\") +\n  theme_plotting()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_plotting()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Does our complex model outperform simple KDE?\"\n  )\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/plot-model-evaluation-1.png){width=1152}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison %>%\n  pivot_longer(everything(), names_to = \"metric\", values_to = \"value\") %>%\n  separate(metric, into = c(\"approach\", \"metric\"), sep = \"_\") %>%\n  pivot_wider(names_from = metric, values_from = value) %>%\n  kable(\n    digits = 2,\n    caption = \"Model Performance Comparison\"\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> approach </th>\n   <th style=\"text-align:right;\"> mae </th>\n   <th style=\"text-align:right;\"> rmse </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> model </td>\n   <td style=\"text-align:right;\"> 2.60 </td>\n   <td style=\"text-align:right;\"> 3.65 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> kde </td>\n   <td style=\"text-align:right;\"> 2.06 </td>\n   <td style=\"text-align:right;\"> 2.95 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate errors\nfishnet <- fishnet %>%\n  mutate(\n    error_nb = countBurglaries - prediction_nb,\n    error_kde = countBurglaries - prediction_kde,\n    abs_error_nb = abs(error_nb),\n    abs_error_kde = abs(error_kde)\n  )\n\n# Map errors\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name = \"Error\",\n    low = \"#2166ac\", mid = \"white\", high = \"#b2182b\",\n    midpoint = 0,\n    limits = c(-10, 10)\n  ) +\n  labs(title = \"Model Errors (Actual - Predicted)\") +\n  theme_plotting()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs. Error\", option = \"magma\") +\n  labs(title = \"Absolute Model Errors\") +\n  theme_plotting()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](assignment4_files/figure-html/plot-errors-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create nice summary table\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(\n    across(where(is.numeric), ~round(., 3))\n  )\n\nmodel_summary %>%\n  kable(\n    caption = \"Final Negative Binomial Model Coefficients (Exponentiated)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(\n    general = \"Rate ratios > 1 indicate positive association with burglary counts.\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Negative Binomial Model Coefficients (Exponentiated)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 7.973 </td>\n   <td style=\"text-align:right;\"> 0.094 </td>\n   <td style=\"text-align:right;\"> 21.990 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> countStreetlights </td>\n   <td style=\"text-align:right;\"> 1.005 </td>\n   <td style=\"text-align:right;\"> 0.006 </td>\n   <td style=\"text-align:right;\"> 0.929 </td>\n   <td style=\"text-align:right;\"> 0.353 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> streetlights_knn </td>\n   <td style=\"text-align:right;\"> 0.996 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -13.325 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> dist_to_hotspot </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -5.569 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate positive association with burglary counts.</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\n\n::: callout-note\n**What we did:**  \n\nWe conclude our analysis by comparing our chosen Negative Binomial model against our baseline KDE model. First, we plotted each model's predictions against the actual burglaries reported in Chicago from 2017. Next, we compared both approaches in terms of performance using MAE and RMSE. Then, we plotted the Negative Binomial model errors and absolute errors side by side. Lastly, we summarized our final model coefficients, printed in the above table.\n\n**What we found:**  \n\n- We found that our Negative Binomial model actually performed worse than the KDE baseline for both metrics of MAE and RSME, meaning that the added complexity of streetlight outages does not benefit our predictions. In other words, crime is better modeled by its own spatial patterns than with factoring in the spatial patterns of streetlight outages.\n\n- From the prediction plots, we see that the Negative Binomial model captures the general structure and patterns of the true reported burglaries better than the KDE baseline. However, we also notice that the burglary hotspots are better captured in the KDE model with a high density of yellow grid cells. This is getting at the root cause of why our KDE baseline has lower error metrics compared to our Negative Binomial model.\n\n- Continuing with our Negative Binomial model evaluation, the maps of the actual and absolute errors reveal why our final model performed worse than our baseline. The Negative Binomial model significantly underpredicted the actual burglary hotspots and slightly overpredicted in cells of lower reported burglary activity, confirming our earlier suspicions of systematic errors in certain Chicago neighborhoods. \n\n- From the Negative Binomial model coefficients, we again see that the spatial variables are statistically significant whereas the raw aggregated cell counts of streetlight outages are not significant from the p-values. For our predictor variable of streetlight outages, this suggests that it matters more where these occur rather than how many there are when predicting burglary activity. \n\n- Lastly, The streetlights_knn variable has a rate-ratio (IRR) of 0.996, reflecting that a closer proximity to streetlight outages leads to a higher predicted burglary count. Mathematically speaking, as the average distance to the three nearest outages increases by 1 meter for each grid cell, there is a 0.4% decrease in predicted burglary counts on average. Interestingly, a rate ratio of 1 for dist_to_hotspot likely signifies a scaling issue since this predictor is statistically significant. In other words, a one-meter change in distance to the nearest burglary hotspot is not enough to alter predicted burglary counts. However, a larger change such as increasing the distance by 1000 meters would have a significant decrease in predicted burglary counts.\n\n**Why this step is important:**  \n\nIt is important to consider why our Negative Binomial performed worse than the KDE baseline. In a way, the KDE baseline overfit our training data by memorizing patterns of high burglary areas and smoothing over them. While this model may perform better, the KDE is much more susceptible to reflecting overpoliced areas and reporting biases rather than truly predicting burglary activity. \n\nAnother issue with our KDE baseline is the lack of interpretability as a non-parametric model compared to our Negative Binomial model. While the KDE may be able to more accurately predict burglary counts, it does not get at the root cause of why burglary hotspots exist, spatial reporting patterns, etc. It simply just tells us where burglaries have occured in the past.\n\nConversely, the Negative Binomial model gets at the root cause of what variables can be attributed to causing high burglary areas in Chicago. We saw that a spatial variable measuring the average distance to the nearest three streetlight outages was significant in predicting burglary counts. We saw that streetlight outages alone did not offer enough predictive power in beating our baseline KDE from our error analysis; however, we believe that incorporating similar spatial variables such as abandoned cars, graffiti locations, etc. can further help improve the model. These variables that align with the \"broken windows theory\" that areas in disarray are more prone to crime could uncover further detail as to understanding and predicting burglary patterns in Chicago.\n\n:::\n",
    "supporting": [
      "assignment4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}